import * as z from "zod";

export const registrationSchema = z
  .object({
    email: z.email("Please provide a valid email"),
    username: z.string().min(3, "Username must be at least 3 characters"),
    password: z.string().min(8, "Password must be at least 8 characters"),
    confirmPassword: z.string(),
    avatarUrl: z.url().optional(),
  })
  .superRefine((data, ctx) => {
    if (data.password !== data.confirmPassword) {
      ctx.addIssue({
        code: "custom",
        message: "Passwords do not match",
        path: ["confirmPassword"], //attach to the CP field
      });
    }
  });

export const loginSchema = z.object({
  email: z.email("Please provide a valid email"),
  password: z.string(),
});

export const walletNonceSchema = z.object({
  // Polygon/EVM addresses are always 42 characters and start with 0x
  address: z
    .string()
    .trim()
    .length(42, "Address must be exactly 42 characters")
    .startsWith("0x", "Address must start with 0x")
    .toLowerCase(), // Gbam: normalize it immediately
});

export const walletVerifySchema = z.object({
  // Must be a valid Ethereum/Polygon address (42 chars, starts with 0x)
  address: z
    .string()
    .trim()
    .length(42, "Invalid wallet address length")
    .regex(/^0x[a-fA-F0-9]{40}$/, "Invalid Ethereum address format"),

  // The hex signature generated by the user's wallet (usually 132 chars)
  signature: z
    .string()
    .trim()
    .min(130, "Signature is too short")
    .startsWith("0x", "Signature must be in hex format"),
});

export const googleSigninSchema = z.object({
  idToken: z.string().trim(),
});
